apiVersion: v1
entries:
  v8s:
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2023-06-12T05:12:37.767246+03:00"
    description: kubernetes controller for vince - The Cloud Native Web Analytics
      Platform.
    digest: 1936b1524b6923961a740c7b5975e071eeaa81d793495f3de263775034b57811
    keywords:
    - vince
    - v8s
    - web analytics
    maintainers:
    - email: geofreyernest@live.com
      name: Geofrey Ernest
    name: v8s
    sources:
    - https://github.com/vinceanalytics/vince
    type: application
    urls:
    - https://vinceanalytics.github.io/charts/v8s-v0.0.10.tgz
    version: v0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2023-06-12T05:12:37.768503+03:00"
    description: kubernetes controller for vince - The Cloud Native Web Analytics
      Platform.
    digest: 64bd0b62977f51238a732eec87746a8c1aca0f2a11ac8ea6b8a88a72edeafc3f
    keywords:
    - vince
    - v8s
    - web analytics
    maintainers:
    - email: geofreyernest@live.com
      name: Geofrey Ernest
    name: v8s
    sources:
    - https://github.com/vinceanalytics/vince
    type: application
    urls:
    - https://vinceanalytics.github.io/charts/v8s-v0.0.9.tgz
    version: v0.0.9
  - apiVersion: v2
    appVersion: v0.0.6
    created: "2023-06-12T05:12:37.768101+03:00"
    description: kubernetes controller for vince - The Cloud Native Web Analytics
      Platform.
    digest: be44ad802d4f5a7f8b8f33018ebaa143ec004842ed1214cb21a4f7605c052248
    keywords:
    - vince
    - v8s
    - web analytics
    maintainers:
    - email: geofreyernest@live.com
      name: Geofrey Ernest
    name: v8s
    sources:
    - https://github.com/vinceanalytics/vince
    type: application
    urls:
    - https://vinceanalytics.github.io/charts/v8s-v0.0.6.tgz
    version: v0.0.6
  - apiVersion: v2
    appVersion: v0.0.3
    created: "2023-06-12T05:12:37.767694+03:00"
    description: kubernetes controller for vince - The Cloud Native Web Analytics
      Platform.
    digest: 04d01fadcf388959e44f20d82f28ffc1600be416ef2f64dbf46a4dd7d37668b9
    keywords:
    - vince
    - v8s
    - web analytics
    maintainers:
    - email: geofreyernest@live.com
      name: Geofrey Ernest
    name: v8s
    sources:
    - https://github.com/vinceanalytics/vince
    type: application
    urls:
    - https://vinceanalytics.github.io/charts/v8s-v0.0.3.tgz
    version: v0.0.3
generated: "2023-06-12T05:12:37.766557+03:00"
